# Generated by Django 4.2.5 on 2023-09-15 00:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="content",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
