# Generated by Django 4.2.5 on 2023-09-15 02:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0002_article_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=models.TextField(default="good"),
        ),
    ]
